services:
  pg-node-1:
    build:
      context: .
      dockerfile: images/test.Dockerfile
    ports:
      - "2222:22"
      - "5433:5432"
      - "8008:8008"
    privileged: true
    networks:
      pgnet:
        ipv4_address: 172.20.0.10

  pg-node-2:
    build:
      context: .
      dockerfile: images/test.Dockerfile
    ports:
      - "2223:22"
      - "5434:5432"
      - "8009:8008"
    privileged: true
    networks:
      pgnet:
        ipv4_address: 172.20.0.11

networks:
  pgnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
