---
services:
  openssh-server:
    build:
      context: .
      dockerfile: images/test.Dockerfile
    container_name: ec2-sim
    ports:
      - "2222:22"
      - 5433:5432
    # Keep container running
    restart: unless-stopped
    privileged: true
