# This script fetches stack outputs for a PostgresStack or PostgresHAStack,
# downloads the SSH key, and generates an ansible inventory file.

STACK_NAME="${1:-PostgresStack}"

echo "fetching stack outputs for $STACK_NAME"

get_output() {
    aws cloudformation describe-stacks \
        --stack-name "$STACK_NAME" \
        --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue | [0]" \
        --output text
}

KEY_NAME=$(get_output "KeyPairPrivateKeyParameterName")

echo "downloading ssh key"
KEY_FILE=~/.ssh/pg-hosting.pem
chmod u+w ~/.ssh/pg-hosting.pem 2>/dev/null || true
aws ssm get-parameter --name "$KEY_NAME" --with-decryption --query "Parameter.Value" --output text > "$KEY_FILE"
chmod 400 "$KEY_FILE"

# Detect stack type by checking for HA-specific output keys
NODE1_IP=$(get_output "Node1PublicIp")

if [ "$NODE1_IP" != "None" ] && [ -n "$NODE1_IP" ]; then
    # HA stack
    NODE2_IP=$(get_output "Node2PublicIp")
    NODE1_PRIVATE=$(get_output "Node1PrivateIp")
    NODE2_PRIVATE=$(get_output "Node2PrivateIp")
    BACKUP_BUCKET=$(get_output "BackupBucketName")
    PATRONI_TABLE=$(get_output "PatroniTableName")

    ssh-keyscan -H "$NODE1_IP" >> ~/.ssh/known_hosts
    ssh-keyscan -H "$NODE2_IP" >> ~/.ssh/known_hosts

    INVENTORY_FILE="inventories/${STACK_NAME}.yml"
    echo "generating HA ansible inventory: $INVENTORY_FILE"
    cat > "$INVENTORY_FILE" <<EOF
# generated by setup.sh for $STACK_NAME
all:
  hosts:
    pg-node-1:
      ansible_host: ${NODE1_IP}
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ${KEY_FILE}
      patroni_node_name: pg-node-1
      patroni_connect_address: ${NODE1_PRIVATE}
      pg_backup_bucket: ${BACKUP_BUCKET}
    pg-node-2:
      ansible_host: ${NODE2_IP}
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ${KEY_FILE}
      patroni_node_name: pg-node-2
      patroni_connect_address: ${NODE2_PRIVATE}
      pg_backup_bucket: ${BACKUP_BUCKET}
  vars:
    patroni_scope: pg-cluster
    patroni_dynamodb_table: ${PATRONI_TABLE}
    aws_region: us-east-1
EOF

    echo "testing connection"
    ansible-playbook -i "$INVENTORY_FILE" playbooks/hello_world.yml

else
    # Single-instance stack
    RHOST=$(get_output "InstancePublicIp")
    BACKUP_BUCKET=$(get_output "BackupBucketName")

    ssh-keyscan -H "$RHOST" >> ~/.ssh/known_hosts

    INVENTORY_FILE="inventories/${RHOST}.yml"
    echo "generating ansible inventory: $INVENTORY_FILE"
    cat > "$INVENTORY_FILE" <<EOF
# generated by setup.sh for $STACK_NAME
myhosts:
  hosts:
    demo:
      ansible_host: ${RHOST}
      ansible_ssh_private_key_file: ${KEY_FILE}
      ansible_user: ec2-user
      pg_backup_bucket: ${BACKUP_BUCKET}
EOF

    echo "testing connection"
    ansible-playbook -i "$INVENTORY_FILE" playbooks/hello_world.yml
fi

echo "done"
