# This script fetches the PublicIP address and SSH Key for an Ec2 stack.
# It adds the host to the known hosts file and saves the SSH key to the .ssh directory.
# It also creates an ansible inventory file for the host and runs the hello world playbook
# to verify the setup is working.

echo "fetching stack outputs"
RHOST=$(aws cloudformation describe-stacks --stack-name PostgresStack --query "Stacks[0].Outputs[?contains(OutputKey, 'InstancePublicIp')].OutputValue | [0]" --output text)
KEY_NAME=$(aws cloudformation describe-stacks --stack-name PostgresStack --query "Stacks[0].Outputs[?contains(OutputKey, 'ParameterName')].OutputValue | [0]" --output text)
BACKUP_BUCKET=$(aws cloudformation describe-stacks --stack-name PostgresStack --query "Stacks[0].Outputs[?contains(OutputKey, 'BackupBucketName')].OutputValue | [0]" --output text)

echo "downloading ssh key"
KEY_FILE=~/.ssh/pg-hosting.pem
chmod u+w ~/.ssh/pg-hosting.pem
aws ssm get-parameter --name $KEY_NAME --with-decryption --query "Parameter.Value" --output text > $KEY_FILE
chmod 400 ~/.ssh/pg-hosting.pem
ssh-keyscan -H $RHOST >> ~/.ssh/known_hosts

echo "generating ansible inventory file"
read -r -d '' MULTILINE_VAR <<EOF
# generated by setup.sh
myhosts:
  hosts:
    demo:
      ansible_host: ${RHOST}
      ansible_ssh_private_key_file: ${KEY_FILE}
      ansible_user: ec2-user
      pg_backup_bucket: ${BACKUP_BUCKET}
EOF
echo "$MULTILINE_VAR" > inventories/${RHOST}.yml

echo "testing connection"
ansible-playbook -i inventories/${RHOST}.yml playbooks/hello_world.yml

echo "done"
