FROM amazonlinux:2023

# Install OpenSSH server and other useful tools
RUN dnf install -y \
    openssh-server \
    openssh-clients \
    sudo \
    python3 \
    which \
    && dnf clean all

# Create SSH host keys
RUN ssh-keygen -A

# Create an ansible user with sudo access
RUN useradd -m -s /bin/bash ansible && \
    echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/ansible && \
    chmod 0440 /etc/sudoers.d/ansible

# Set up SSH directory for ansible user
RUN mkdir -p /home/ansible/.ssh && \
    chmod 700 /home/ansible/.ssh && \
    chown ansible:ansible /home/ansible/.ssh

# Copy in the public key for passwordless SSH auth
# (generated by docker-compose or passed in at build time)
COPY ansible_key.pub /home/ansible/.ssh/authorized_keys
RUN chmod 600 /home/ansible/.ssh/authorized_keys && \
    chown ansible:ansible /home/ansible/.ssh/authorized_keys

# Configure SSH: disable root login, enable key auth
RUN sed -i \
    -e 's/#PermitRootLogin.*/PermitRootLogin no/' \
    -e 's/#PubkeyAuthentication.*/PubkeyAuthentication yes/' \
    -e 's/#AuthorizedKeysFile.*/AuthorizedKeysFile .ssh\/authorized_keys/' \
    -e 's/#PasswordAuthentication.*/PasswordAuthentication no/' \
    /etc/ssh/sshd_config

EXPOSE 2222
EXPOSE 5432

CMD ["/usr/sbin/init", "-D", "-e"]
