#!/bin/bash
# Fetches Trino stack outputs, downloads the SSH key, and generates an inventory.
# Usage: ./services/trino/setup.sh [StackName]

set -euo pipefail

STACK_NAME="${1:-Trino}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "fetching stack outputs for $STACK_NAME"

get_output() {
    aws cloudformation describe-stacks \
        --stack-name "$STACK_NAME" \
        --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue | [0]" \
        --output text
}

KEY_NAME=$(get_output "KeyPairPrivateKeyParameterName")
RHOST=$(get_output "InstancePublicIp")
BUCKET=$(get_output "BucketName")
REGION=$(get_output "Region")

echo "downloading ssh key"
KEY_FILE=~/.ssh/trino-hosting.pem
chmod u+w "$KEY_FILE" 2>/dev/null || true
aws ssm get-parameter --name "$KEY_NAME" --with-decryption --query "Parameter.Value" --output text > "$KEY_FILE"
chmod 400 "$KEY_FILE"

ssh-keyscan -H "$RHOST" >> ~/.ssh/known_hosts

INVENTORY_FILE="$SCRIPT_DIR/inventories/${STACK_NAME}.yml"
echo "generating inventory: $INVENTORY_FILE"
cat > "$INVENTORY_FILE" <<EOT
# generated by setup.sh for $STACK_NAME
all:
  hosts:
    trino:
      ansible_host: ${RHOST}
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ${KEY_FILE}
      # replaces the default dict in group_vars, so tpch is repeated here
      trino_catalogs:
        tpch:
          connector.name: tpch
        iceberg:
          connector.name: iceberg
          iceberg.catalog.type: glue
          hive.metastore.glue.region: ${REGION}
          hive.metastore.glue.default-warehouse-dir: s3://${BUCKET}/warehouse
          fs.s3.enabled: "true"
          s3.region: ${REGION}
EOT

echo "testing connection"
ansible-playbook -i "$INVENTORY_FILE" "$SCRIPT_DIR/../hello_world/playbooks/hello_world.yml"

echo "done"
